Fix test failures exposed in Python 3.8
[pbauer]